name: love_test_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  audioplayers: ^0.20.1
  vibration: ^1.7.6
  simple_animations: ^4.0.1
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  flutter_spinkit: ^5.1.0
  supercharged: ^2.1.1
  confetti: ^0.7.0
  liquid_progress_indicator: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_screenutil: ^5.6.0

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/bg_image.png
    - assets/audio/
    - assets/


  fonts:
    - family: BuiltTitlingRg
      fonts:
        - asset: assets/fonts/builtTitlingRGFont.ttf


