name: love_test_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  audioplayers: ^0.20.1
  vibration: ^1.7.6
  simple_animations: ^4.0.1
  provider: ^6.0.5
  shared_preferences: ^2.0.16
  flutter_spinkit: ^5.1.0
  supercharged: ^2.1.1
  confetti: ^0.7.0
  liquid_progress_indicator: ^0.4.0
  easy_ads_flutter:
    git:
      url: https://github.com/nooralibutt/easy-ads
      ref: facebook-pre-release
  flutter_screenutil: ^5.6.0
  app_tracking_transparency: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"

flutter_native_splash:
  color: "#ffffff"  # required parameter
  image: assets/splash.png
  android_gravity: fill
  ios_content_mode: scaleToFill

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg_image.png
    - assets/audio/
    - assets/

  fonts:
    - family: BuiltTitlingRg
      fonts:
        - asset: assets/fonts/builtTitlingRGFont.ttf


