name: love_test_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_screenutil: ^5.6.0

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/bg_image.png
    - assets/audio/


  fonts:
    - family: BuiltTitlingRg
      fonts:
        - asset: assets/fonts/builtTitlingRGFont.ttf


